---
# Ensure that cloud-config is enabled and enable the others while we're at it.
- name: Enable all cloud-init services
  hosts: all
  become: true
  become_method: ansible.builtin.sudo
  tasks:
    - name: Enable all cloud-init services
      ansible.builtin.service:
        name: "{{ item }}"
        enabled: true
      loop:
        - cloud-config
        - cloud-final
        - cloud-init
        - cloud-init-local
