---
# Ensure that cloud-config is enabled and enable the others while we're at it.
- hosts: all
  name: Enable all cloud-init services
  become: yes
  become_method: ansible.builtin.sudo
  tasks:
    - name: Enable all cloud-init services
      ansible.builtin.service:
        name: "{{ item }}"
        enabled: yes
      loop:
        - cloud-config
        - cloud-final
        - cloud-init
        - cloud-init-local
