---
- hosts: all
  name: Install Auto-Egress-Assess tool
  become: yes
  become_method: sudo
  roles:
    - role: assessment_tool
      vars:
        archive_src: https://github.com/tarrell13/Auto-Egress-Assess/tarball/main
        install_dir: /tools/Auto-Egress-Assess
        pip_requirements_file: requirements.txt
        powershell: yes
        unarchive_extra_opts:
          - --strip-components=1
