---
- hosts: all
  name: Install Auto-Egress-Assess tool
  become: yes
  become_method: ansible.builtin.sudo
  tasks:
    - name: Install tarrell13/Auto-Egress-Assess
      ansible.builtin.include_role:
        name: assessment_tool
      vars:
        assessment_tool_archive_src: https://github.com/tarrell13/Auto-Egress-Assess/tarball/main
        assessment_tool_install_dir: /tools/Auto-Egress-Assess
        assessment_tool_pip_requirements_file: requirements.txt
        assessment_tool_powershell: yes
        assessment_tool_unarchive_extra_opts:
          - --strip-components=1
