---
- hosts: all
  name: Install Egress-Assess tool
  become: yes
  become_method: sudo
  roles:
    - role: assessment_tool
      vars:
        archive_src: "https://github.com/ChrisTruncer/Egress-Assess/\
        tarball/master"
        install_dir: /tools/Egress-Assess
        pip_packages:
          - pyftpdlib
        powershell: yes
        python2: yes
        unarchive_extra_opts:
          - --strip-components=1
