---
- name: Import base image playbook
  ansible.builtin.import_playbook: base.yml

- name: Import AWS playbook
  ansible.builtin.import_playbook: aws.yml

- name: Import cloud-init playbook
  ansible.builtin.import_playbook: cloud_init.yml

# The AWS playbook must run before this one, since this playbook uses
# a user group created in the AWS playbook.
- name: Import VNC playbook
  ansible.builtin.import_playbook: vnc.yml

# The VNC playbook must run before this one, since this playbook uses
# a user created in the VNC playbook.
- name: Import Xfce playbook
  ansible.builtin.import_playbook: xfce.yml

- name: Import Egress-Assess playbook
  ansible.builtin.import_playbook: egress_assess.yml
