---
- name: Import base image playbook
  ansible.builtin.import_playbook: base.yml

- name: Import AWS playbook
  ansible.builtin.import_playbook: aws.yml

- name: Import Egress-Assess playbook
  ansible.builtin.import_playbook: egress_assess.yml
